name: Swift Test On GSat
description: Execute swift package manager tests on a GSat.

runs:
  using: 'composite'

  steps:
    - name: Build Tests
      if: ${{ runner.os == 'Linux' }}
      run: |
        PKG_CONFIG_PATH="/usr/local/armv7-unknown-linux-gnueabihf/staging/lib/pkgconfig:$PKG_CONFIG_PATH" swift build --build-tests --destination /usr/local/armv7-unknown-linux-gnueabihf/destination.json
        buildPath=`PKG_CONFIG_PATH="/usr/local/armv7-unknown-linux-gnueabihf/staging/lib/pkgconfig:$PKG_CONFIG_PATH" swift build --show-bin-path --destination /usr/local/armv7-unknown-linux-gnueabihf/destination.json`
        scp $buildPath/${{ github.event.repository.name }}PackageTests.xctest runner@petalinux.local:~/
        ssh runner@petalinux.local /home/runner/${{ github.event.repository.name }}PackageTests.xctest
        ssh runner@petalinux.local rm -r /home/runner/${{ github.event.repository.name }}PackageTests.xctest
      shell: bash
